name: multimodal_va_liga
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - scikit-learn
  - matplotlib
  - jupyterlab
  - cudatoolkit=11.8.0 
  - cudnn
  - pip
  - pip:
      - uv
      - tensorflow
      - opencv-python
      - transformers
      - pydub